export { Hero } from './Hero'
export { Services } from './Services'
export { Process } from './Process'
export { Stack } from './Stack'
export { Projects } from './Projects'
export { FAQ } from './FAQ'
export { Contact } from './Contact'
