# Generated by Django 4.2.27 on 2025-12-21 02:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('contact', models.CharField(max_length=180, verbose_name='Contacto (email/teléfono)')),
                ('project_type', models.CharField(blank=True, max_length=60, verbose_name='Tipo de proyecto')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('timeframe', models.CharField(blank=True, max_length=40, verbose_name='Plazo estimado')),
                ('budget_range', models.CharField(blank=True, max_length=40, verbose_name='Presupuesto aproximado')),
                ('reference_url', models.URLField(blank=True, verbose_name='URL de referencia')),
                ('has_domain_hosting', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene dominio/hosting?')),
                ('source', models.CharField(default='form', max_length=30, verbose_name='Fuente')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('scheduled', 'Agendado'), ('canceled', 'Cancelado'), ('contacted', 'Contactado'), ('won', 'Ganado'), ('lost', 'Perdido'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Estado')),
                ('spam_score', models.IntegerField(default=0, verbose_name='Puntuación de spam')),
                ('ip_hash', models.CharField(blank=True, max_length=80, verbose_name='Hash de IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('calendly_invitee_uri', models.TextField(blank=True, verbose_name='Calendly Invitee URI')),
                ('calendly_event_uri', models.TextField(blank=True, verbose_name='Calendly Event URI')),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de reunión agendada')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60, verbose_name='Tipo de evento')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Payload original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Evento de Lead',
                'verbose_name_plural': 'Eventos de Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
